libreorganize/apps/boxes/urls.py
from apps.boxes import views
from django.urls import path

app_name = "apps.boxes"

urlpatterns = [
    path("", views.ListView.as_view(), name="list"),
    path("<int:uid>/edit/", views.EditView.as_view(), name="edit"),
    path("upload/", views.UploadView.as_view(), name="upload"),
    path("upload/<int:pk>/delete/", views.DeleteUploadView.as_view(), name="delete"),
]

libreorganize/apps/memberships/urls.py
from apps.memberships import views
from django.urls import path

app_name = "apps.memberships"

urlpatterns = [
    path("", views.ListView.as_view(), name="list"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("enroll/", views.EnrollView.as_view(), name="enroll"),
    path("renewal/", views.RenewalListView.as_view(), name="renewal"),
    path("<int:uid>/", views.DetailView.as_view(), name="detail"),
    path("<int:uid>/edit/", views.EditView.as_view(), name="edit"),
    path("<int:uid>/delete/", views.DeleteView.as_view(), name="delete"),
]

libreorganize/apps/memberships/models.py
from django.utils.timezone import now

from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.accounts.models import Account


class Membership(models.Model):
    uid = models.AutoField(primary_key=True)
    kind = models.CharField(max_length=16, choices=settings.MEMBERSHIP_TYPES, default="normal")
    start_date = models.DateField(help_text=_("Must be formatted as YYYY-MM-DD"))
    end_date = models.DateField(default=now, blank=True, help_text=_("Must be formatted as YYYY-MM-DD"))
    membership_period = models.CharField(max_length=16, choices=settings.MEMBERSHIP_PERIOD, default="one_year")
    payment_method = models.CharField(max_length=8, choices=settings.PAYMENT_METHODS, default="cash")
    member = models.OneToOneField(
        Account,
        on_delete=models.CASCADE,
        error_messages={"unique": _("There is already a membership associated with this account.")},
    )
    is_active = models.BooleanField(default=False)

    class Meta:
        default_permissions = ()
        permissions = (
            ("list_memberships", "List memberships"),
            ("create_memberships", "Create memberships"),
            ("edit_memberships", "Edit memberships"),
            ("delete_memberships", "Delete memberships"),
            ("view_memberships", "View memberships"),
        )


class MembershipLog(models.Model):
    uid = models.AutoField(primary_key=True)
    member = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    kind = models.CharField(max_length=16, choices=settings.MEMBERSHIP_TYPES, default="normal")
    renewal_period_start = models.DateField(help_text=_("Must be formatted as YYYY-MM-DD"))
    renewal_period_end = models.DateField(default=now, blank=True, help_text=_("Must be formatted as YYYY-MM-DD"))

    class Meta:
        default_permissions = ()

libreorganize/apps/memberships/forms.py
import datetime

from dateutil.relativedelta import relativedelta
from django import forms
from django.conf import settings
from django.utils.translation import gettext_lazy as _

from tempus_dominus.widgets import DatePicker

from apps.memberships.models import Membership


class EnrollForm(forms.ModelForm):
    class Meta:
        model = Membership
        fields = ["kind", "payment_method"]
        labels = {"kind": "Type", "payment_method": "Payment Method"}


class CreateForm(forms.ModelForm):
    class Meta:
        model = Membership
        fields = ["kind", "start_date", "member"]
        labels = {"kind": "Type", "start_date": "Start Date", "member": "Member"}
        widgets = {
            "start_date": DatePicker(
                options={
                    "format": "YYYY-MM-DD",
                    "icons": {"up": "fas fa-chevron-up fa-fw", "down": "fas fa-chevron-down fa-fw",},
                },
                attrs={"append": "fas fa-calendar-alt fa-fw"},
            ),
        }

    def save(self, commit=True):
        self.instance.payment_method = "cash"
        self.instance.is_active = False
        return super().save(commit)


class EditForm(forms.ModelForm):
    class Meta:
        model = Membership
        fields = ["kind", "start_date", "membership_period", "payment_method", "member", "is_active"]
        labels = {
            "kind": "Type",
            "start_date": "Start Date",
            "membership_period": "Membership Period",
            "payment_method": "Payment Method",
            "member": "Member",
            "is_active": "Active",
        }
        widgets = {
            "start_date": DatePicker(
                options={
                    "format": "YYYY-MM-DD",
                    "icons": {"up": "fas fa-chevron-up fa-fw", "down": "fas fa-chevron-down fa-fw"},
                },
                attrs={"append": "fas fa-calendar-alt fa-fw"},
            ),
        }

    def __init__(self, *args, **kwargs):
        super(EditForm, self).__init__(*args, **kwargs)
        self.fields["member"].disabled = True

    def save(self, commit=True):
        # Set the end_date based on the renewal period
        delta = relativedelta(years=1)
        if self.cleaned_data["membership_period"] == "one_month":
            delta = relativedelta(months=1)
        self.instance.end_date = self.instance.start_date + delta

        return super().save(commit)

libreorganize/apps/memberships/views.py
import datetime

from django.conf import settings
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.mail import send_mail
from django.utils.translation import gettext_lazy as _
from django.views.generic import ListView as GenericListView

from core.mixins import AccessRestrictedMixin
from core.views import LibreDeleteView, LibreCreateView, LibreUpdateView, LibreDetailView
from apps.memberships.models import Membership, MembershipLog
from apps.memberships.forms import EnrollForm, CreateForm, EditForm


class ListView(AccessRestrictedMixin, GenericListView):
    permissions = "memberships.list_memberships"
    model = Membership


class RenewalListView(AccessRestrictedMixin, GenericListView):
    permissions = "memberships.view_memberships"
    model = MembershipLog


class DetailView(AccessRestrictedMixin, LibreDetailView):
    permissions = ("memberships.view_memberships",)
    personal = True
    model = Membership
    pk_url_kwarg = "uid"


class DeleteView(AccessRestrictedMixin, LibreDeleteView):
    permissions = ("memberships.delete_memberships",)
    personal = True
    model = Membership
    pk_url_kwarg = "uid"
    success_url = reverse_lazy("memberships:list")
    success_message = _("The membership has been deleted.")


class EditView(AccessRestrictedMixin, LibreUpdateView):
    permissions = ("memberships.edit_memberships",)
    model = Membership
    form_class = EditForm
    pk_url_kwarg = "uid"
    success_url = reverse_lazy("memberships:list")
    success_message = _("The membership has been successfully edited.")


class CreateView(AccessRestrictedMixin, LibreCreateView):
    permissions = ("memberships.create_memberships",)
    model = Membership
    form_class = CreateForm
    success_url = reverse_lazy("memberships:list")
    success_message = _("The membership has been successfully created.")


class EnrollView(AccessRestrictedMixin, LibreCreateView):
    model = Membership
    form_class = EnrollForm
    success_url = "/"

    def get_success_message(self, cleaned_data):
        return f"Congratulations, {self.request.user.first_name}! You are almost a member of {settings.SITE_NAME}. An administrator will activate your membership soon."

    def dispatch(self, request, *args, **kwargs):
        if hasattr(request.user, "membership"):
            messages.add_message(request, messages.ERROR, _("You are already a member!"))
            return HttpResponseRedirect(self.success_url)
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        # Fill in some default values
        form.instance.start_date = datetime.date.today()
        form.instance.member = self.request.user
        result = super().form_valid(form)

        # Send an email to the administrator
        url = self.request.build_absolute_uri(f"/memberships/{form.instance.uid}/")
        html = render_to_string(
            "email.html",
            {
                "url": url,
                "message": _(
                    "A member who is paying by cash has joined! Login to activate his membership. Edit Membership and make the Account Active once you have recieved the money."
                ),
                "button": "View Membership",
            },
        )
        text = strip_tags(html).replace("View Membership", url)
        send_mail(
            subject=_("New Member | %s ") % settings.SITE_NAME,
            message=text,
            html_message=html,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=(settings.NOTIFICATIONS_EMAIL,),
            fail_silently=True,
        )

        return result

libreorganize/apps/memberships/templates/memberships/enroll.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans 'Enroll' %}{% endblock %}

{% block content %}
<div class="row no-gutters card-row">
    <div class="col-lg-5 col-md-7 col-sm-9 col-11 mx-auto my-auto">
        <div class="card">
            <div class="card-header">
                <h1 class="text-center">{% trans "Enroll" %}</h1>
            </div>
            <div class="card-body">
                <form novalidate method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="form-actions text-center">
                        <button type="submit" class="btn btn-primary card-btn">{% trans "Submit" %}</button>
                        <a href="{{ view.success_url }}" class="btn btn-secondary card-btn">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

libreorganize/apps/memberships/templates/memberships/membership_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans 'Delete Membership' %}{% endblock %}

{% block content %}
<div class="row no-gutters card-row">
    <div class="col-lg-5 col-md-7 col-sm-9 col-11 mx-auto my-auto">
        <div class="card">
            <div class="card-header">
                <h1 class="text-center">{% trans "Delete Membership" %}</h1>
            </div>
            <div class="card-body">
                <form novalidate method="post">
                    {% csrf_token %}
                    <div class="form-group text-center">
                        {% trans "Are you sure you want to delete this membership?" %}
                        <br>
                        {% trans "This action is irreversible." %}
                        <br>
                        <br>
                        {% trans "There will be no more charges related to this membership." %}
                    </div>
                    <div class="form-actions text-center">
                        <button type="submit" class="btn btn-danger card-btn">{% trans "Delete" %}</button>
                        <a href="{{ view.success_url }}" class="btn btn-secondary card-btn">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

libreorganize/apps/memberships/templates/memberships/membership_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'View Membership' %}{% endblock %}

{% block content %}
<div class="row no-gutters card-row">
    <div class="col-11 mx-auto my-auto">
        <div class="card">
            <div class="card-header">
                <h1 class="text-center">{% trans 'View Membership' %}</h1>
            </div>
            <div class="card-body">
                <div class="container">
                    <div class="row no-gutters">
                        <div class="col-lg-3 text-center">
                            <a class="btn btn-info detail-btn" href="{% url 'accounts:detail' uid=membership.member.uid %}">{% trans "View Account" %}</a>
                            {% if perms.memberships.edit_memberships %}
                            <a class="btn btn-warning detail-btn"
                                href="{% url 'memberships:edit' uid=membership.uid %}?next={{ request.get_full_path }}">{% trans "Edit Membership" %}</a>
                            {% endif %}
                            {% if perms.memberships.delete_memberships %}
                            <a class=" btn btn-danger detail-btn" href="{% url 'memberships:delete' uid=membership.uid %}?next={{ request.get_full_path }}">{% trans "Delete Membership" %}</a>
                            {% endif %}
                        </div>
                        <div class="col-lg-8 offset-lg-1">
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <tbody>
                                        <tr>
                                            <th scope="row">UID</th>
                                            <td>{{ membership.uid }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">{% trans "Member" %}</th>
                                            <td>{{ membership.member.get_full_name }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">{% trans "Type" %}</th>
                                            <td>{{ membership.get_kind_display }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">{% trans "Start Date" %}</th>
                                            <td>{{ membership.start_date }}</td>
                                        </tr>
                                        {% if membership.is_active %}
                                        <tr>
                                            <th scope="row">{% trans "Expiration Date" %}</th>
                                            <td>{{ membership.end_date }}</td>
                                        </tr>
                                        {% endif %}
                                        <tr>
                                            <th scope="row">{% trans "Payment Method" %}</th>
                                            <td>{{ membership.get_payment_method_display }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">{% trans "Active" %}</th>
                                            <td>{{ membership.is_active|yesno:"Yes,No" }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

libreorganize/apps/memberships/templates/memberships/membership_form.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% if object %}{% trans 'Edit Membership' %}{% else %}{% trans 'Create Membership' %}{% endif %}{% endblock %}
{% block extra_head %}
{{ form.media }}
{% endblock %}

{% block content %}
<div class="row no-gutters card-row">
    <div class="col-lg-5 col-md-7 col-sm-9 col-11 mx-auto my-auto">
        <div class="card">
            <div class="card-header">
                <h1 class="text-center">{% if object %}{% trans 'Edit Membership' %}{% else %}{% trans 'Create Membership' %}{% endif %}</h1>
            </div>
            <div class="card-body">
                <form novalidate method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="form-actions text-center">
                        <button type="submit" class="btn btn-primary card-btn">{% trans "Submit" %}</button>
                        <a href="{{ view.success_url }}" class="btn btn-secondary card-btn">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

libreorganize/apps/memberships/templates/memberships/membership_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Memberships' %}{% endblock %}

{% block content %}
<div class="row no-gutters card-row">
    <div class="col-11 mx-auto my-auto">
        <div class="card">
            <div class="card-header">
                <h1 class="text-center">{% trans "Memberships" %}</h1>
            </div>
            <div class="card-body">
                <table id="jsTable" class="table table-striped nowrap" style="width: 100%;">
                    <thead>
                        <tr>
                            <th scope="col">UID</th>
                            <th scope="col">{% trans "Member" %}</th>
                            <th scope="col">{% trans "Start/Payment Date" %}</th>
                            <th scope="col">{% trans "Expiration Date" %}</th>
                            <th scope="col">{% trans "Type" %}</th>
                            <th scope="col">{% trans "Active" %}</th>
                            <th scope="col">
                                {% if perms.memberships.create_memberships %}
                                <a class="btn btn-sm btn-success" href="{% url 'memberships:create' %}?next={{ request.get_full_path }}">
                                    <i class="fas fa-plus fa-fw"></i>
                                </a>
                                {% endif %}
                                {% if perms.memberships.view_memberships %}
                                <a class="btn btn-sm btn-info" href="{% url 'memberships:renewal' %}">
                                    <i class="fas fa-history fa-fw"></i>
                                </a>
                                {% endif %}
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for membership in object_list %}
                        <tr>
                            <td>{{ membership.uid }}</td>
                            <td>{{ membership.member }}</td>
                            <td>{{ membership.start_date }}</td>
                            <td>{{ membership.end_date }}</td>
                            <td>{{ membership.get_kind_display }}</td>
                            <td>{{ membership.is_active|yesno:"Yes,No" }}</td>
                            <td>
                                {% if perms.memberships.view_memberships %}
                                <a class="btn btn-sm btn-info" href="{% url 'memberships:detail' uid=membership.uid %}"><i class="fas fa-eye fa-fw"></i></a>
                                {% endif %}
                                {% if perms.memberships.edit_memberships %}
                                <a class="btn btn-sm btn-warning" href="{% url 'memberships:edit' uid=membership.uid %}?next={{ request.get_full_path }}"><i
                                        class="fas fa-pen fa-fw"></i></a>
                                {% endif %}
                                {% if perms.memberships.delete_memberships %}
                                <a class="btn btn-sm btn-danger" href="{% url 'memberships:delete' uid=membership.uid %}?next={{ request.get_full_path }}"><i
                                        class="fas fa-trash fa-fw"></i></a>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

libreorganize/apps/memberships/templates/memberships/membershiplog_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Memberships' %}{% endblock %}

{% block content %}
<div class="row no-gutters card-row">
    <div class="col-11 mx-auto my-auto">
        <div class="card">
            <div class="card-header">
                <h1 class="text-center">{% trans "Membership Renewal" %}</h1>
            </div>
            <div class="card-body">
                <table id="jsTable" class="table table-striped nowrap" style="width: 100%;">
                    <thead>
                        <tr>
                            <th scope="col">UID</th>
                            <th scope="col">{% trans "Member" %}</th>
                            <th scope="col">{% trans "Start/Payment Date" %}</th>
                            <th scope="col">{% trans "End Date" %}</th>
                            <th scope="col">{% trans "Amount" %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for membership in object_list %}
                        <tr>
                            <td>{{ membership.uid }}</td>
                            <td><a href="{% url 'memberships:detail' uid=membership.uid %}">{{ membership.member }}</a></td>
                            <td>{{ membership.renewal_period_start }}</td>
                            <td>{{ membership.renewal_period_end  }}</td>
                            <td>{{ membership.get_kind_display }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}