libreorganize/apps/accounts/urls.py
from django.urls import path

from apps.accounts import views

app_name = "apps.accounts"

urlpatterns = [
    path("", views.ListView.as_view(), name="list"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("password/reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path("password/reset/<uidb64>/<token>/", views.PasswordResetConfirmView.as_view(), name="password_reset"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("<int:uid>/password/change/", views.PasswordChangeView.as_view(), name="password_change"),
    path("<int:uid>/", views.DetailView.as_view(), name="detail"),
    path("<int:uid>/edit/", views.EditView.as_view(), name="edit"),
    path("<int:uid>/delete/", views.DeleteView.as_view(), name="delete"),
    path("<int:uid>/permissions/edit/", views.EditPermissionsView.as_view(), name="permissions_edit"),
    path("<int:uid>/attendance/", views.AttendanceView.as_view(), name="attendance"),
]

libreorganize/apps/boxes/urls.py
from apps.boxes import views
from django.urls import path

app_name = "apps.boxes"

urlpatterns = [
    path("", views.ListView.as_view(), name="list"),
    path("<int:uid>/edit/", views.EditView.as_view(), name="edit"),
    path("upload/", views.UploadView.as_view(), name="upload"),
    path("upload/<int:pk>/delete/", views.DeleteUploadView.as_view(), name="delete"),
]

libreorganize/apps/accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import gettext_lazy as _
from django_countries.fields import CountryField

from apps.accounts.managers import AccountManager
from apps.polls.models import Poll


class Account(AbstractBaseUser, PermissionsMixin):
    uid = models.AutoField(primary_key=True)
    email = models.EmailField(unique=True, error_messages={"unique": _("This email is already in use.")})
    title = models.CharField(max_length=8, choices=settings.TITLE_CHOICES, blank=True)
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)

    date_of_birth = models.DateField(blank=True, null=True, help_text=_("Must be formatted as YYYY-MM-DD"))
    gender = models.CharField(choices=settings.GENDER_CHOICES, max_length=8, blank=True)
    company = models.CharField(max_length=64, blank=True)
    phone = models.CharField(max_length=16, blank=True, help_text=_("Must not have any spaces, parentheses, or dashes"))
    address1 = models.CharField(max_length=96, blank=True, help_text=_("Street address, P.O. box"))
    address2 = models.CharField(max_length=64, blank=True, help_text=_("Apartment, suite, unit, building, floor"))
    city = models.CharField(max_length=32, blank=True)
    state = models.CharField(max_length=32, blank=True)
    zipcode = models.CharField(max_length=16, blank=True)
    country = CountryField(blank_label="", blank=True)
    polls = models.ManyToManyField(Poll)
    notification = models.BooleanField(blank=True, default=False)

    avatar = models.ImageField(upload_to="img/avatars", blank=True, help_text=_("Use a 1:1 image for the best quality"))

    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    objects = AccountManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        default_permissions = ()
        permissions = (
            ("list_accounts", "List accounts"),
            ("view_accounts", "View accounts"),
            ("edit_accounts", "Edit accounts"),
            ("delete_accounts", "Delete accounts"),
            ("change_passwords", "Change passwords"),
            ("access_dashboard", "Access dashboard"),
        )

    @property
    def avatar_url(self):
        if self.avatar:
            return self.avatar.url
        return settings.STATIC_URL + "img/profile_avatar.png"

    @property
    def phone_number(self):
        if len(self.phone) == 10:
            return "(" + self.phone[:3] + ") " + self.phone[3:6] + "-" + self.phone[6:10]
        elif (len(self.phone) == 12 or len(self.phone) == 13) and self.phone[0] == "+":
            return self.phone[:-10] + " (" + self.phone[-10:-7] + ") " + self.phone[-7:-4] + "-" + self.phone[-4:]
        else:
            return self.phone

    def __str__(self):
        return self.get_full_name()

    def get_full_name(self):
        return self.first_name + " " + self.last_name

    def get_short_name(self):
        return self.first_name + " " + self.last_name[:1] + "."

    def get_full_address(self):
        full_address = ""
        if self.address1:
            full_address = self.address1
            if self.address2:
                full_address += ", "
                full_address += self.address2
        if self.city:
            if full_address != "":
                full_address += ", "
            full_address += self.city
        if self.state:
            if full_address != "":
                full_address += ", "
            full_address += self.state
        if self.zipcode:
            if full_address != "":
                full_address += " "
            full_address += self.zipcode
        if self.country:
            if full_address != "":
                full_address += ", "
            full_address += self.country.name
        return full_address

libreorganize/apps/events/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.conf import settings

from apps.accounts.models import Account


class Event(models.Model):
    uid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=48)
    description = models.TextField(blank=True)
    start_date = models.DateTimeField(help_text=_("Must be formatted as YYYY-MM-DD HH:MM"))
    end_date = models.DateTimeField(help_text=_("Must be formatted as YYYY-MM-DD HH:MM"))
    location = models.CharField(max_length=128, help_text=_("Should be an address"))
    max_participants = models.IntegerField(default=-1, help_text="Enter -1 for an unlimited number of participants")
    participants = models.ManyToManyField(Account, blank=True)
    is_private = models.BooleanField(default=False, help_text="Must be logged in to view the event")
    occurrences = models.IntegerField(default=1, help_text="Must be a value between 1 and 12")
    frequency = models.CharField(
        choices=settings.FREQUENCY_CHOICES,
        help_text="Ignore if there is only one occurrence",
        max_length=12,
        default="weekly",
    )
    previous = models.OneToOneField(
        "Event", on_delete=models.CASCADE, null=True, editable=False, related_name="subsequent"
    )
    sent = models.BooleanField(default=False)

    class Meta:
        default_permissions = ()
        permissions = (
            ("list_events", "List events"),
            ("create_events", "Create events"),
            ("edit_events", "Edit events"),
            ("delete_events", "Delete events"),
        )

libreorganize/apps/accounts/views.py
from django.conf import settings
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.shortcuts import render
from django.contrib.auth import login, authenticate, logout
from django.template.loader import render_to_string
from django.contrib.auth.tokens import default_token_generator as token_generator
from django.utils.encoding import force_bytes, force_text
from django.utils.translation import gettext_lazy as _
from django.utils.encoding import force_text
from django.utils.html import strip_tags
from django.core.mail import send_mail
from django.utils.http import urlsafe_base64_decode
from django.views import View
from django.views.generic import ListView
from django.views.generic.base import ContextMixin

from core.mixins import AccessRestrictedMixin, AccessModelMixin, NextPageMixin
from apps.accounts.forms import *
from core.views import LibreDeleteView, LibreDetailView, LibreUpdateView, LibreCreateView


class ListView(AccessRestrictedMixin, ListView):
    permissions = ("accounts.list_accounts", "accounts.edit_accounts", "accounts.delete_accounts")
    model = Account


class DetailView(AccessRestrictedMixin, LibreDetailView):
    personal = True
    permissions = ("accounts.view_accounts", "accounts.edit_accounts", "accounts.delete_accounts")
    model = Account
    pk_url_kwarg = "uid"


class CreateView(AccessRestrictedMixin, LibreCreateView):
    superuser = True
    template_name = "accounts/account_create.html"
    form_class = AccountForm
    success_url = "/accounts/"
    success_message = _("The account has been successfully created.")

    def post(self, request):
        form = AccountForm(request.POST)
        if form.is_valid():
            account = form.save(commit=False)
            account.is_superuser = False
            account.save()

            url = request.build_absolute_uri("/accounts/password/reset/")
            url += urlsafe_base64_encode(force_bytes(account.uid)) + "/"
            url += token_generator.make_token(account) + "/"

            html = render_to_string(
                "email.html",
                {
                    "url": url,
                    "message": f"{account.first_name}, activate your new account using the link below.",
                    "button": "Activate Account",
                },
            )
            text = strip_tags(html).replace("Activate Account", url)

            send_mail(
                subject="Activate Account | LibreOrganize",
                message=text,
                html_message=html,
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=(account.email,),
                fail_silently=True,
            )
            messages.success(self.request, self.success_message)
            return HttpResponseRedirect(reverse("accounts:list"))
        return render(request=request, template_name="accounts/account_create.html", context={"form": form})


class EditView(AccessRestrictedMixin, LibreUpdateView):
    personal = True
    permissions = "accounts.edit_accounts"
    model = Account
    form_class = EditForm
    pk_url_kwarg = "uid"
    success_url = reverse_lazy("accounts:list")
    success_message = _("The account has been successfully edited.")


class DeleteView(AccessRestrictedMixin, LibreDeleteView):
    permissions = "accounts.delete_accounts"
    model = Account
    pk_url_kwarg = "uid"
    success_url = reverse_lazy("accounts:list")
    success_message = _("The account has been successfully deleted.")


class LoginView(View):
    def dispatch(self, request):
        self.next = request.GET.get("next", None)
        if not self.next or "://" in self.next or " " in self.next:
            self.next = "/"
        if request.user.is_authenticated:
            messages.add_message(request, messages.WARNING, _("You are already logged in!"))
            return HttpResponseRedirect(self.next)
        return super().dispatch(request)

    def get(self, request):
        form = LoginForm()
        return render(request=request, template_name="accounts/login.html", context={"form": form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.login(request):
            messages.add_message(
                request,
                messages.SUCCESS,
                _(f"Welcome back, {request.user.first_name}! You have successfully logged in."),
            )
            return HttpResponseRedirect(self.next)
        return render(request=request, template_name="accounts/login.html", context={"form": form})


class LogoutView(View):
    def get(self, request):
        if request.user.is_authenticated:
            logout(request)
            messages.add_message(request, messages.SUCCESS, _("You have successfully logged out."))
        else:
            messages.add_message(request, messages.WARNING, _("You are already logged out!"))
        return HttpResponseRedirect(reverse("home"))


class RegisterView(NextPageMixin, ContextMixin, View):
    def dispatch(self, request):
        if request.user.is_authenticated:
            messages.add_message(request, messages.WARNING, _("You cannot register an account while being logged in!"))
            return HttpResponseRedirect(reverse("home"))
        return super().dispatch(request)

    def get(self, request):
        form = RegistrationForm()
        return render(request=request, template_name="accounts/register.html", context=self.get_context_data(form=form))

    def post(self, request):
        form = RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                _(
                    f"Welcome to {settings.SITE_NAME}, {form.cleaned_data['first_name']}! You have successfully registered."
                ),
            )
            return HttpResponseRedirect(reverse("accounts:login"))
        return render(request=request, template_name="accounts/register.html", context=self.get_context_data(form=form))


class PasswordResetView(View):
    def dispatch(self, request):
        if request.user.is_authenticated:
            messages.add_message(
                request,
                messages.WARNING,
                _("You have been redirected to change your password because you are logged in!"),
            )
            return HttpResponseRedirect(reverse("accounts:password_change", args={request.user.uid}))
        return super().dispatch(request)

    def get(self, request):
        form = PasswordResetForm()
        return render(request=request, template_name="accounts/password/reset.html", context={"form": form})

    def post(self, request):
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            form.save(request=request)
            messages.add_message(
                request, messages.SUCCESS, _("You have successfully requested a password reset."),
            )
            return HttpResponseRedirect(reverse("accounts:login"))
        return render(request=request, template_name="accounts/password/reset.html", context={"form": form})


class PasswordResetConfirmView(NextPageMixin, ContextMixin, View):
    def dispatch(self, request, uidb64, token):
        if request.user.is_authenticated:
            messages.add_message(
                request,
                messages.WARNING,
                _("You have been redirected to change your password because you are logged in!"),
            )
            return HttpResponseRedirect(reverse("accounts:password_change", args={request.user.uid}))
        try:
            self.account = Account.objects.get(uid=force_text(urlsafe_base64_decode(uidb64)))
            if token_generator.check_token(self.account, token):
                return super().dispatch(request)
            raise Account.DoesNotExist
        except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
            messages.add_message(request, messages.ERROR, _("The request is invalid."))
            return HttpResponseRedirect(reverse("accounts:password_reset"))

    def get(self, request):
        form = PasswordResetConfirmForm()
        return render(
            request=request, template_name="accounts/password/reset.html", context=self.get_context_data(form=form)
        )

    def post(self, request):
        form = PasswordResetConfirmForm(request.POST)
        if form.is_valid():
            form.save(account=self.account)
            messages.add_message(request, messages.SUCCESS, _("You have successfully reset your password."))
            return HttpResponseRedirect(reverse("accounts:login"))
        return render(
            request=request, template_name="accounts/password/reset.html", context=self.get_context_data(form=form)
        )


class PasswordChangeView(AccessRestrictedMixin, AccessModelMixin, NextPageMixin, ContextMixin, View):
    permissions = ("accounts.change_passwords",)
    personal = True
    model = Account

    def get(self, request):
        form = PasswordChangeForm()
        return render(
            request=request, template_name="accounts/password/change.html", context=self.get_context_data(form=form)
        )

    def post(self, request):
        form = PasswordChangeForm(request.POST)
        if form.is_valid():
            form.save(self.account)
            messages.add_message(request, messages.SUCCESS, _("You have successfully changed the password."))
            return HttpResponseRedirect(self.next)
        return render(
            request=request, template_name="accounts/password/change.html", context=self.get_context_data(form=form)
        )


class EditPermissionsView(AccessRestrictedMixin, AccessModelMixin, NextPageMixin, ContextMixin, View):
    permissions = "accounts.delete_accounts"
    model = Account

    def get(self, request):

libreorganize/apps/accounts/templates/accounts/account_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Delete Account' %}{% endblock %}

{% block content %}
<div class="row no-gutters card-row">
    <div class="col-lg-5 col-md-7 col-sm-9 col-11 mx-auto my-auto">
        <div class="card">
            <div class="card-header">
                <h1 class="text-center">{% trans "Delete Account" %}</h1>
            </div>
            <div class="card-body">
                <form novalidate method="post">
                    {% csrf_token %}
                    <div class="form-group text-center">
                        {% trans "Are you sure you want to delete this account?" %}
                        <br>
                        {% trans "This action is irreversible." %}
                    </div>
                    <div class="form-actions text-center">
                        <button type="submit" class="btn btn-danger card-btn">{% trans "Delete" %}</button>
                        <a href="{{ view.success_url }}" class="btn btn-secondary card-btn">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

libreorganize/apps/accounts/templates/accounts/account_create.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans 'Create' %}{% endblock %}
{% block extra_head %}
{{ form.media }}
<style>
    .asteriskField {
        display: inline;
    }
</style>
{% endblock %}

{% block content %}
<div class="row no-gutters card-row">
    <div class="col-lg-5 col-md-7 col-sm-9 col-11 mx-auto my-auto">
        <div class="card">
            <div class="card-header">
                <h1 class="text-center">{% trans "Create Account" %}</h1>
            </div>
            <div class="card-body">
                <form novalidate method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="form-actions text-center">
                        <button type="submit" class="btn btn-primary card-btn">{% trans "Submit" %}</button>
                        <a href="{% url 'accounts:list' %}" class="btn btn-secondary card-btn">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

libreorganize/apps/accounts/templates/accounts/account_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{{ account.get_full_name }}{% endblock %}
{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block content %}
<div class="row no-gutters card-row">
    <div class="col-11 mx-auto my-auto">
        <div class="card">
            <div class="card-header">
                <h1 class="text-center">{{ account.get_full_name }}</h1>
            </div>
            <div class="card-body">
                <div class="container">
                    <div class="row no-gutters">
                        <div class="col-lg-3 text-center">
                            <img class="img-detail" src="{{ account.avatar_url }}">
                            {% if account.membership %}
                            <a class=" btn btn-info detail-btn"
                                href="{% url 'memberships:detail' uid=account.membership.uid %}">{% trans "View Membership" %}</a>
                            {% endif %}
                            {% if request.user.uid == account.uid or perms.accounts.view_accounts %}
                            <a class=" btn btn-info detail-btn" href="{% url 'accounts:attendance' uid=account.uid %}">{% trans "View Attendance History" %}</a>
                            {% endif %}
                            {% if perms.accounts.delete_accounts %}
                            <a class="btn btn-warning detail-btn"
                                href="{% url 'accounts:permissions_edit' uid=account.uid %}?next={{ request.get_full_path }}">{% trans "Edit Permissions" %}</a>
                            {% endif %}
                            {% if request.user.uid == account.uid or perms.accounts.edit_accounts %}
                            <a class="btn btn-warning detail-btn"
                                href="{% url 'accounts:edit' uid=account.uid %}?next={{ request.get_full_path }}">{% trans "Edit Account" %}</a>
                            {% endif %}
                            {% if request.user.uid == account.uid or perms.accounts.change_passwords %}
                            <a class="btn btn-danger detail-btn" href="{% url 'accounts:password_change' uid=account.uid %}?next={{ request.get_full_path }}">{% trans "Change Password" %}</a>
                            {% endif %}
                            {% if perms.accounts.delete_accounts %}
                            <a class=" btn btn-danger detail-btn" href="{% url 'accounts:delete' uid=account.uid %}?next={{ request.get_full_path }}">{% trans "Delete Account" %}</a>
                            {% endif %}
                        </div>
                        <div class="col-lg-8 offset-lg-1">
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <tbody>
                                        <tr>
                                            <th scope="row">UID</th>
                                            <td>{{ account.uid }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">{% trans "Title" %}</th>
                                            <td>{{ account.get_title_display }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">{% trans "First Name" %}</th>
                                            <td>{{ account.first_name }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">{% trans "Last Name" %}</th>
                                            <td>{{ account.last_name }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">{% trans "Email" %}</th>
                                            <td>{{ account.email }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">{% trans "Phone Number" %}</th>
                                            <td>{{ account.phone_number }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">{% trans "Date of Birth" %}</th>
                                            <td>{{ account.date_of_birth|default_if_none:"" }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">{% trans "Gender" %}</th>
                                            <td>{{ account.get_gender_display }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">{% trans "Company / School / University" %}</th>
                                            <td>{{ account.company }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">{% trans "Address Line 1" %}</th>
                                            <td>{{ account.address1 }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">{% trans "Address Line 2" %}</th>
                                            <td>{{ account.address2 }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">{% trans "City" %}</th>
                                            <td>{{ account.city }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">{% trans "State / Region / Province" %}</th>
                                            <td>{{ account.state }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">{% trans "ZIP / Postal Code" %}</th>
                                            <td>{{ account.zipcode }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">{% trans "Country" %}</th>
                                            <td>{{ account.country.name }} <img src="{{ account.country.flag }}"></td>
                                        </tr>
                                        <tr>
                                        <th scope="row">{% trans "Event Notification" %}</th>
                                            <td>{{ account.notification|yesno:"Yes, No" }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">{% trans "Last Login" %}</th>
                                            <td>{{ account.last_login }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">{% trans "Active" %}</th>
                                            <td>{{ account.is_active|yesno:"Yes,No" }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">{% trans "Superuser" %}</th>
                                            <td>{{ account.is_superuser|yesno:"Yes,No" }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

libreorganize/apps/accounts/templates/accounts/account_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Accounts' %}{% endblock %}

{% block content %}
<div class="row no-gutters card-row">
    <div class="col-11 mx-auto my-auto">
        <div class="card">
            <div class="card-header">
                <h1 class="text-center">{% trans "Accounts" %}</h1>
            </div>
            <div class="card-body">
                <table id="jsTable" class="table table-striped nowrap" style="width: 100%;">
                    <thead>
                        <tr>
                            <th scope="col">UID</th>
                            <th scope="col">{% trans "First Name" %}</th>
                            <th scope="col">{% trans "Last Name" %}</th>
                            <th scope="col">{% trans "Email" %}</th>
                            <th scope="col">{% trans "Phone Number" %}</th>
                            <th scope="col">{% trans "# Events" %}</th>
                            <th scope="col">
                                <a class="btn btn-sm btn-success" href="{% url 'accounts:create' %}?next={{ request.get_full_path }}" title="Create Account"><i
                                        class="fas fa-plus fa-fw"></i></a>
                            </th>                
                        </tr>
                    </thead>
                    <tbody>
                        {% for account in object_list %}
                        <tr>
                            <td>{{ account.uid }}</td>
                            <td>{{ account.first_name }}</td>
                            <td>{{ account.last_name }}</td>
                            <td>{{ account.email }}</td>
                            <td>{{ account.phone_number }}</td>
                            <td>{{ account.event_set.count }}</td>
                            <td>
                                {% if perms.accounts.view_accounts %}
                                <a class="btn btn-sm btn-info" href="{% url 'accounts:detail' uid=account.uid %}"><i class="fas fa-eye fa-fw"></i></a>
                                {% endif %}
                                {% if perms.accounts.edit_accounts %}
                                <a class="btn btn-sm btn-warning" href="{% url 'accounts:edit' uid=account.uid %}"><i
                                        class="fas fa-pen fa-fw"></i></a>
                                {% endif %}
                                {% if perms.accounts.delete_accounts %}
                                <a class="btn btn-sm btn-danger" href="{% url 'accounts:delete' uid=account.uid %}"><i
                                        class="fas fa-trash fa-fw"></i></a>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}